#include <core.p4>
#include <tna.p4>

//            .="=.
//          _/.-.-.\_
//         ( ( o o ) )
//          |/  "  \|
//           \ --- /
//           /`"""`\
//          / /_,_\ \
//          \_\_'__/_
//            /   \
//           /_/ \_\

// Types of incoming packets:
// wanpatan
// <metadata.hdr><eth.hdr><payload>: A normal packet entering Tofino for the first time
// <metadata.hdr><cpu.hdr><eth.hdr><payload>: A packet from or destined for the CPU
// <metadata.hdr><resubmit.hdr><eth.hdr><payload>: A packet passing through Tofino for the second time
// <metadata.hdr><pktgen_port_down.hdr>: A packet generated by pktgen when a port goes down

// Ethernet header
header ethernet_t {
    bit<48> dst_addr;
    bit<48> src_addr;
    bit<16> ether_type;
}

// Resubmit header
// When a packet is resubmitted for a second pass,
// Tofino adds a resubmit flag on ingress.
// If set, the packet also contains this header.
header resubmit_md_t {
    bit<32> orig_ts32;
    bit<16> orig_ingress_port;
    bit<16> pad;
}

// CPU header
// For CPU->DP: code is the reason it was recirculated
// For DP->CPU: code is the opcode specifying what to do
header cpu_header_t {
    bit<3>  code;
    bit<5>  pad;
    bit<16> forward;
    bit<32> ts32;
}

// Packet generator header triggered by port down (commented out because TNA already defines it)
//header pktgen_port_down_header_t {
//    @padding bit<3> _pad1;
//    bit<2> pipe_id;
//    bit<3> app_id;
//    @padding bit<(16 - PORT_ID_WIDTH % 8)> _pad2;
//    PortId_t port_num;
//    bit<16> packet_id;
//}

// Complete header stack (not all headers need to be present)
struct headers_t {
    resubmit_md_t resub;
    pktgen_port_down_header_t port_down;
    cpu_header_t  cpu;
    ethernet_t    ethernet;
}

// Metadata added to the packet descriptor throughout the pipeline
struct metadata_t {
    bit<48>  lookup_mac; // MAC address to look up (source or destination)
    bit<1>   lookup_hit; // Whether the lookup hit (1) or missed (0)
    PortId_t lookup_port; // Port read from the table on a hit
    bit<1>   lookup_port_match; // Whether the table port matches the ingress port

    bit<2>   lookup_time_result; // Timestamp of the table entry
    bit<8>   lookup_valid; // Whether the entry was valid (1) or invalid (0)
    bit<1>   valid_invalidate; // Whether to invalidate the entry in addition to reading the flag

    bit<1>   is_second_pass; // Flag derived from the resubmit indication in the Tofino header

    PortId_t flood_src_port; // Source port (may otherwise be lost on resubmit)

    bit<3>   cpu_redirect_code; // Reason or opcode for CPU communication
    bit<16>  cpu_redirect_original_port; // Metadata for the field used by the CPU

    bit<32>  ts32; // Preserve the packet arrival timestamp for processing
    bit<32>  reg_dir; // Indirect register index associated with the table entry
    
    bit<1> is_pktgen_port_down; // Whether this packet was generated by a port-down trigger

    bit<1> output_port_up; // Whether the output port is up
}

struct empty_metadata_t {
}

////////////////////
// Ingress parser //
////////////////////

// The first ingress block takes the deserialized packet
// and extracts information into the packet descriptor, which is
// the logical reference P4 uses for the incoming packet.

// Works as a small state machine
// 
// ---------------------------------------------
// Initial state: start
// Zero all variables to avoid using uninitialized values
// Extract IngressIntrinsicMetadata: ig_intr_md, the header added by Tofino described above, containing
// the ingress port, arrival timestamp, and recirculation or resubmit indication
//
// Next state:
// - If resubmit is 1: start -> parse resubmit
// - If resubmit is 0 and 64 bits follow -> parse CPU
// - Otherwise -> default: remove metadata (the unused header, not ingress metadata)
// -------------------------------------------------
//
// -------------------------------------------------
// Parse CPU state:
// Parse the header added by the controller when returning a CPU->Data plane packet; its opcode tells
// the data plane what to do.
//
// Next state:
// - Go to default -> remove metadata (the unused header, not ingress metadata)
// -------------------------------------------------
//
// -------------------------------------------------
// Parse resubmit state:
// Parse the header inserted on resubmit, containing the original timestamp and port
//
// Next state:
// - Go to default -> remove metadata (the unused header, not ingress metadata)
// -------------------------------------------------
//
// -------------------------------------------------
// Default state:
// Remove metadata (the unused header, not ingress metadata)
//
// Next state:
// - Go to parse Ethernet -> parse the Ethernet header
// -------------------------------------------------
//
// -------------------------------------------------
// Parse Ethernet state:
// Parse Ethernet and accept -> proceed to the ingress pipeline
// -------------------------------------------------

parser SwitchIngressParser(
    packet_in packet,
    out headers_t hdr,
    out metadata_t md,
    out ingress_intrinsic_metadata_t ig_intr_md
) {
    state start {
        
        // Initialize descriptor variables to zero to avoid uninitialized values

        // Headers initially invalid
		hdr.resub.setInvalid();
		hdr.cpu.setInvalid();
		hdr.port_down.setInvalid();
		hdr.ethernet.setInvalid();

        // Table lookup fields
        md.lookup_mac = 0;
        md.lookup_hit = 0;
        md.lookup_port = 0;
        md.lookup_port_match = 0;

        // Register lookup action fields
        md.lookup_time_result = 0;
        md.lookup_valid = 0;
        md.valid_invalidate = 0;

        // Packet classification fields
        md.is_second_pass = 0;
        md.flood_src_port = 0;

        // CPU fields
        md.cpu_redirect_code = 0;
        md.cpu_redirect_original_port = 0;

        // Other fields
        md.ts32 = 0;
        md.reg_dir = 0;
        
        // Packet generator
        md.is_pktgen_port_down = 0; // Initially assume the packet is not from a port_down event

        // Port state
        md.output_port_up = 0;


        packet.extract(ig_intr_md); // Extract metadata

        transition select (ig_intr_md.resubmit_flag, ig_intr_md.ingress_port) {
            (1, _)   : parse_resubmit;
            (0, 64)  : parse_cpu;
            (0, 68)  : parse_pktgen_port_down;
            default  : skip_port_metadata;
        }
    }

    state parse_resubmit {
        // hdr.resub = packet.lookahead<resubmit_md_t>();
        // packet.advance(PORT_METADATA_SIZE);
        packet.extract(hdr.resub);
        transition parse_ethernet;
    }

    state parse_cpu {
        packet.advance(PORT_METADATA_SIZE);
        packet.extract(hdr.cpu);
        transition parse_ethernet;
    }
    
    state parse_pktgen_port_down {
	    packet.advance(PORT_METADATA_SIZE);
	    packet.extract(hdr.port_down);
	    md.is_pktgen_port_down = 1;
	    transition accept;
	}

    state skip_port_metadata {
        packet.advance(PORT_METADATA_SIZE);
        transition parse_ethernet;
    }

    state parse_ethernet {
        packet.extract(hdr.ethernet);
        transition accept;
    }
}

/////////////
// Ingress //
/////////////

// The main processing logic
// The flow is somewhat complex; the following summarizes it.
// A packet arrives.
// 
// --------------------------------------
// If it comes from the packet generator
// --------------------------------------
// A port monitored by the packet generator has gone down. Notify the CPU directly so it can
// take the appropriate action (pkt_action 4).
//
// ---------------------------------------------------
// If this is the first pass (neither resubmit nor CPU)
// ---------------------------------------------------
// - Analyze the source MAC and decide whether to learn and whether to drop or proceed to the second pass
// - First, look up mac_state using the source MAC
// - On a hit
//   - If the source port differs from the stored port
//     - Set the flag to invalidate the entry
//     - Examine the entry timestamp
//     - If packet timestamp - entry timestamp > BLOCK_TIME_CTE
//       - Invalidate the entry (it is no longer locked)
//       - Send the packet to the CPU to delete the entry and create a new one
//     - Otherwise
//       - Drop the packet because the entry is locked
//       - Do not refresh the entry timestamp
// - On a miss
//   - Send to the CPU with the learn reason
//
// ---------------------------------------------------
// If resubmitted (second pass of normal flow)
// ---------------------------------------------------
// - Analyze the destination MAC to choose where to forward a packet that passed the first stage
// - Look up mac_state using the destination MAC
// - On a hit
//   - If the entry is valid
//     - If the entry has expired: packet timestamp - entry timestamp > ENTRY_MAX_AGE_CTE
//       - Invalidate the entry and send the packet to the CPU
//     - Otherwise
//       - If the entry is still locked: packet timestamp - entry timestamp < BLOCK_TIME_CTE
//         - Do not update the entry timestamp
//       - Otherwise
//         - Update to timestamp - BLOCK_TIME_CTE to keep the entry outside the blocking window
//   - If the entry is invalid
//     - Flood
// - On a miss
//   - Flood
//
// -------------------------------------------------------------
// If from the CPU (with an opcode specifying what to do)
// -------------------------------------------------------------
// - Execute the decision already made by the CPU
// - The packet arrives with cpu_header
// - Read the opcode and forward field
// - Invalidate the CPU header so it is not transmitted externally
// - If the opcode is CPU_TO_DP_CODE_UNICAST
//   - Interpret forward as the output port
//   - Send the packet by unicast to that port
// - If the opcode is CPU_TO_DP_CODE_MULTICAST
//   - Interpret forward as the original ingress port
//   - Use that port to look up flood_by_ingress
//   - Send through the flood group associated with that ingress port
// - If the opcode is unrecognized
//   - Drop the packet
// - This path does not query mac_state
// - This path does not resubmit
// - This path does not learn in the data plane

control SwitchIngress(
    inout headers_t hdr,
    inout metadata_t md,
    in ingress_intrinsic_metadata_t ig_intr_md,
    in ingress_intrinsic_metadata_from_parser_t ig_intr_prsr_md,
    inout ingress_intrinsic_metadata_for_deparser_t ig_intr_dprsr_md,
    inout ingress_intrinsic_metadata_for_tm_t ig_intr_tm_md
) {
    const bit<32> BLOCK_TIME_CTE    = 32w30518; // Approximately two seconds (not entirely sure, but it seems so)
    const bit<32> ENTRY_MAX_AGE_CTE = 32w915527; // Approximately 120 seconds (uncertain)

    const PortId_t CPU_ETHERNET_PORT = 9w64; // CPU device ports are 64 and 67

    const bit<3> CPU_TO_DP_CODE_UNICAST   = 3w0; // Opcode received from the CPU for unicast forwarding
    const bit<3> CPU_TO_DP_CODE_MULTICAST = 3w1; // Opcode received from the CPU for multicast group forwarding

    const bit<3> DP_TO_CPU_CODE_LEARN = 3w0; // Reason sent to the CPU when learning or moving a MAC is required
    const bit<3> DP_TO_CPU_CODE_AGED  = 3w1; // Reason sent to the CPU when an entry has aged out
    const bit<3> DP_TO_CPU_CODE_PORT_DOWN = 3w2; // Reason sent to the CPU when the packet comes from a port-down event
    const bit<3> DP_TO_CPU_CODE_PORT_UNAVAILABLE = 3w3; // Reason sent to the CPU when forwarding was attempted through a failed port
    
    // [Note] First-pass aging initially seemed unhandled. However,
    // an aged entry is already unlocked, so when its source MAC arrives,
    // the entry is refreshed or deleted.

	

    Register<bit<32>, bit<32>>(65536) mac_state_tstamp; // Packet timestamps are 48 bits, but the SALUs cannot process that width
    // Use 32 bits with a shift, sacrificing some precision
    Register<bit<8>,  bit<32>>(65536) mac_state_valid;

    // Register actions

    // valid_access: check entry validity and invalidate it if the invalidation flag is 1
    // Operates on the validity register
    RegisterAction<bit<8>, bit<32>, bit<8>>(mac_state_valid) valid_access = {
        void apply(inout bit<8> value, out bit<8> result) {
            result = value;

            if (md.valid_invalidate == 1) {
                value = 8w0;
            }
        }
    };

    // tstamp_first_pass: read the timestamp register on the first pass (without resubmit)
    // Check whether the entry has expired and update it as appropriate
    // Operates on the ts32 register on the first pass
    RegisterAction<bit<32>, bit<32>, bit<2>>(mac_state_tstamp) tstamp_first_pass = {
        void apply(inout bit<32> value, out bit<2> result) {
            bit<32> diff;
            diff = md.ts32 - value;

            if (diff > BLOCK_TIME_CTE) {
                result = 2w1;
            } else {
                result = 2w0;
            }

            if (md.lookup_port_match == 1) {
                value = md.ts32;
            }
        }
    };

    // tstamp_second_pass: read the timestamp register on the second pass (with resubmit)
    // Check whether the entry has aged out and update it if necessary
    // Operates on the ts32 register on the second pass
    RegisterAction<bit<32>, bit<32>, bit<2>>(mac_state_tstamp) tstamp_second_pass = {
        void apply(inout bit<32> value, out bit<2> result) {
            bit<32> diff;
            diff = md.ts32 - value;

            if (diff > ENTRY_MAX_AGE_CTE) {
                result = 2w1;
            } else {
                result = 2w0;

                if (diff > BLOCK_TIME_CTE) {
                    value = md.ts32 - BLOCK_TIME_CTE;
                }
            }
        }
    };

    // Table actions (reminder: defining an action is not enough; the controller must assign it to a table entry)

    // Port status actions (return 1 or 0 depending on whether the port is up)
    action port_status_hit(bit<1> is_up) {
        md.output_port_up = is_up;
    }

    action port_status_miss() {
        md.output_port_up = 0;
    }


    // mac_hit: set the hit flag and record it in a register
    // Always operates on mac_state
    action mac_hit(PortId_t port, bit<32> reg_dir) {
        md.lookup_hit = 1;
        md.lookup_port = port;
        md.reg_dir = reg_dir;
    }
    
    // mac_hit: set the hit flag and record it in a register
    // Always operates on mac_state
    action mac_miss() {
        md.lookup_hit = 0;
        md.lookup_port = 0;
        md.lookup_port_match = 0;
        md.lookup_time_result = 0;
        md.lookup_valid = 0;
        md.valid_invalidate = 0;
        md.reg_dir = 0;
    }

    // Always include this action to avoid unexpected behavior
    // Used as the default action for all tables and as a function outside them
    action drop() {
        ig_intr_dprsr_md.drop_ctl = 0x1;
    }

    // Functions
    
    // Set the unicast output port
    action set_unicast(PortId_t port) {
        ig_intr_tm_md.ucast_egress_port = port;
    }

    // Set the destination node in the PRE
    action set_flood_grp(bit<16> gid) {
        ig_intr_tm_md.mcast_grp_a = gid;
    }

    // Tables

    // Port status table: whether the port is up
    table port_status {
        key = {
            md.lookup_port : exact;
        }
        actions = {
            port_status_hit;
            port_status_miss;
        }
        const default_action = port_status_miss();
        size = 288;
    }

    // MAC table: key = MAC; values = port and register index for validity and timestamp (set by the controller)
    table mac_state {
        key = {
            md.lookup_mac : exact;
        }
        actions = {
            mac_hit;
            mac_miss;
        }
        const default_action = mac_miss();
        size = 65536;
    }

    // PRE table: obtain the group ID from the source port
    // Key = source port; value = group ID (set by the controller)
    table flood_by_ingress {
        key = {
            md.flood_src_port : exact;
        }
        actions = {
            set_flood_grp;
            @defaultonly drop;
        }
        const default_action = drop();
        size = 288;
    }

    apply {
        // Local variables
        bit<3> pkt_action;
        bit<1> from_cpu;
        bit<1> dst_is_group;
        bit<1> do_mac_lookup;

        bit<1> src_old_enough;
        bit<1> dst_aged;

        bit<3> cpu_code;
        bit<16> cpu_forward;

        // Initialize variables

        ig_intr_dprsr_md.resubmit_type = 0;
        ig_intr_tm_md.bypass_egress = 0;

        pkt_action = 0;
        from_cpu = 0;
        dst_is_group = 0;
        do_mac_lookup = 0;

        src_old_enough = 0;
        dst_aged = 0;

        cpu_code = 0;
        cpu_forward = 0;

        md.lookup_hit = 0;
        md.lookup_port = 0;
        md.lookup_port_match = 0;

        md.lookup_time_result = 0;
        md.lookup_valid = 0;
        md.valid_invalidate = 0;

        md.is_second_pass = 0;
        md.reg_dir = 0;

        md.cpu_redirect_code = 0;
        md.cpu_redirect_original_port = 0;

        // Processing starts here
        
        if (md.is_pktgen_port_down == 1) { // Packet generator packet triggered by port down
			if (hdr.port_down.app_id == 3w3) { // App ID 3 (generated by port down)
				md.cpu_redirect_code = DP_TO_CPU_CODE_PORT_DOWN;
				md.cpu_redirect_original_port = (bit<16>) hdr.port_down.port_num;
				md.ts32 = (bit<32>)(ig_intr_prsr_md.global_tstamp >> 16);
				
                // Add an L2 header because the Xeon NIC otherwise drops the packet
                
                hdr.ethernet.setValid();
                hdr.ethernet.dst_addr = 48w0xffffffffffff;
                hdr.ethernet.src_addr = 48w0x020000000001;
                hdr.ethernet.ether_type = 16w0x9000;
                
                
                
                pkt_action = 4;
			} else {
				pkt_action = 0;
			}
		}
		else { // Otherwise
		    if (hdr.cpu.isValid()) {
		        from_cpu = 1;
		    } else {
		        from_cpu = 0;
		    }

		    if (from_cpu == 1) {
		        cpu_code = hdr.cpu.code;
		        cpu_forward = hdr.cpu.forward;

		        hdr.cpu.setInvalid();

		        if (cpu_code == CPU_TO_DP_CODE_UNICAST) {
		            md.lookup_port = (PortId_t) cpu_forward;
		            pkt_action = 2;
		        } else if (cpu_code == CPU_TO_DP_CODE_MULTICAST) {
		            md.flood_src_port = (PortId_t) cpu_forward;
		            pkt_action = 3;
		        } else {
		            pkt_action = 0;
		        }
		    } else {
		        if (ig_intr_md.resubmit_flag == 0) {
		            md.is_second_pass = 0;
		            md.ts32 = (bit<32>)(ig_intr_prsr_md.global_tstamp >> 16);
		            md.lookup_mac = hdr.ethernet.src_addr;
		            md.flood_src_port = ig_intr_md.ingress_port;
		            do_mac_lookup = 1;
		        } else {
		            md.is_second_pass = 1;
		            md.ts32 = hdr.resub.orig_ts32;
		            md.flood_src_port = (PortId_t) hdr.resub.orig_ingress_port;

		            dst_is_group = hdr.ethernet.dst_addr[40:40];

		            if (dst_is_group == 0) {
		                md.lookup_mac = hdr.ethernet.dst_addr;
		                do_mac_lookup = 1;
		            } else {
		                do_mac_lookup = 0;
		            }
		        }

		        if (do_mac_lookup == 1) {
		            mac_state.apply();

		            if (md.lookup_hit == 1) {
		                if (md.lookup_port == md.flood_src_port) {
		                    md.lookup_port_match = 1;
		                } else {
		                    md.lookup_port_match = 0;
		                }
		            } else {
		                md.lookup_port_match = 0;
		            }
		        }

		        if (ig_intr_md.resubmit_flag == 0) {
		            if (md.lookup_hit == 0) {
		                md.cpu_redirect_code = DP_TO_CPU_CODE_LEARN;
		                md.cpu_redirect_original_port = (bit<16>) ig_intr_md.ingress_port;
		                pkt_action = 4;
		            } else {
		                md.lookup_time_result = tstamp_first_pass.execute(md.reg_dir);
		                src_old_enough = md.lookup_time_result[0:0];

		                if ((md.lookup_port_match == 0) && (src_old_enough == 1)) {
		                    md.valid_invalidate = 1;
		                } else {
		                    md.valid_invalidate = 0;
		                }

		                md.lookup_valid = valid_access.execute(md.reg_dir);

		                if (md.lookup_valid == 8w0) {
		                    md.cpu_redirect_code = DP_TO_CPU_CODE_LEARN;
		                    md.cpu_redirect_original_port = (bit<16>) ig_intr_md.ingress_port;
		                    pkt_action = 4;
		                } else {
		                    if (md.lookup_port_match == 1) {
		                        pkt_action = 1;
		                    } else {
		                        if (src_old_enough == 1) {
		                            md.cpu_redirect_code = DP_TO_CPU_CODE_LEARN;
		                            md.cpu_redirect_original_port = (bit<16>) ig_intr_md.ingress_port;
		                            pkt_action = 4;
		                        } else {
		                            pkt_action = 0;
		                        }
		                    }
		                }
		            }
		        } else {
		            if (dst_is_group == 1) {
		                pkt_action = 3;
		            } else {
		                if (md.lookup_hit == 0) {
		                    pkt_action = 3;
		                } else {
		                    md.lookup_time_result = tstamp_second_pass.execute(md.reg_dir);
		                    dst_aged = md.lookup_time_result[0:0];

		                    if (dst_aged == 1) {
		                        md.valid_invalidate = 1;
		                    } else {
		                        md.valid_invalidate = 0;
		                    }

		                    md.lookup_valid = valid_access.execute(md.reg_dir);

		                    if (md.lookup_valid == 8w0) {
		                        pkt_action = 3;
		                    } else {
		                        if (dst_aged == 1) {
		                            md.cpu_redirect_code = DP_TO_CPU_CODE_AGED;
		                            md.cpu_redirect_original_port = 16w0;
		                            pkt_action = 4;
		                        } else {
		                            pkt_action = 2;
		                        }
		                    }
		                }
		            }
		        }
		    }
	    }

        if (pkt_action == 0) {
            drop();
        }

        if (pkt_action == 1) {
            ig_intr_dprsr_md.resubmit_type = 1;
        }

        if (pkt_action == 2) {
            port_status.apply(); // Look up the port

            if (md.output_port_up == 1) { // If up, send through it
                ig_intr_tm_md.bypass_egress = 1;
                set_unicast(md.lookup_port);
            }
            else { // If down, send to the CPU for handling
                ig_intr_tm_md.bypass_egress = 1;

                hdr.cpu.setValid();
                hdr.cpu.code = DP_TO_CPU_CODE_PORT_UNAVAILABLE;
                hdr.cpu.pad = 0;
                hdr.cpu.forward = (bit<16>) md.flood_src_port;
                hdr.cpu.ts32 = md.ts32;

                hdr.port_down.setInvalid();

                set_unicast(CPU_ETHERNET_PORT);
            }
        }

        if (pkt_action == 3) {
            ig_intr_tm_md.bypass_egress = 1;
            flood_by_ingress.apply();
        }

        if (pkt_action == 4) {
            ig_intr_tm_md.bypass_egress = 1;
			
            hdr.cpu.setValid();
            hdr.cpu.code = md.cpu_redirect_code;
            hdr.cpu.pad = 0;
            hdr.cpu.forward = md.cpu_redirect_original_port;
            hdr.cpu.ts32 = md.ts32;

			hdr.port_down.setInvalid();

            set_unicast(CPU_ETHERNET_PORT);
        }
    }
}

//////////////////////
// Ingress deparser //
//////////////////////

control SwitchIngressDeparser(
    packet_out pkt,
    inout headers_t hdr,
    in metadata_t md,
    in ingress_intrinsic_metadata_for_deparser_t ig_intr_dprsr_md
) {
    Resubmit() resubmit;

    apply {
        if (ig_intr_dprsr_md.resubmit_type == 1) {
            hdr.resub.setValid();
            hdr.resub.orig_ts32 = md.ts32;
            hdr.resub.orig_ingress_port = (bit<16>) md.flood_src_port;
            hdr.resub.pad = 0;
            resubmit.emit(hdr.resub);
        }

        pkt.emit(hdr.cpu);
        pkt.emit(hdr.ethernet);
    }
}

///////////////////
// Egress parser //
///////////////////

parser SwitchEgressParser(
    packet_in pkt,
    out headers_t hdr,
    out empty_metadata_t eg_md,
    out egress_intrinsic_metadata_t eg_intr_md
) {
    state start {
        pkt.extract(eg_intr_md);
        transition accept;
    }
}

////////////
// Egress //
////////////

control SwitchEgress(
    inout headers_t hdr,
    inout empty_metadata_t eg_md,
    in egress_intrinsic_metadata_t eg_intr_md,
    in egress_intrinsic_metadata_from_parser_t eg_intr_md_from_prsr,
    inout egress_intrinsic_metadata_for_deparser_t eg_intr_dprs_md,
    inout egress_intrinsic_metadata_for_output_port_t eg_intr_oport_md
) {
    apply {
    }
}

/////////////////////
// Egress deparser //
/////////////////////

control SwitchEgressDeparser(
    packet_out pkt,
    inout headers_t hdr,
    in empty_metadata_t eg_md,
    in egress_intrinsic_metadata_for_deparser_t eg_intr_dprs_md
) {
    apply {
    }
}

// Finally, define the complete pipeline

Pipeline(
    SwitchIngressParser(),
    SwitchIngress(),
    SwitchIngressDeparser(),
    SwitchEgressParser(),
    SwitchEgress(),
    SwitchEgressDeparser()
) pipe;

Switch(pipe) main;
